const REAL_ESTATE_JOKES = [
  "Why did the real estate agent bring a ladder? The market was looking up.",
  "I tried to sell my house without an agent—but I just couldn't handle the listing pressure.",
  "Why do real estate agents make great detectives? They always follow up on their leads.",
  "That house has a lot of character. Unfortunately, most of it is in the foundation.",
  "Why was the tiny house so confident? It had nothing to prove—it knew its square footage.",
  "I have a joke about a roof, but it might go over your head.",
  "Why did the house go to therapy? It had too many unresolved issues in the basement.",
  "The open house was a huge success. Everyone agreed the front door was very welcoming.",
  "My real estate agent promised me a great deal. She really delivered on the closing statement.",
  "Why did the realtor carry a pencil? To draw up an offer.",
  "I bought a house near the ocean. It was a shore thing.",
  "Why are houses so good at keeping secrets? Because their walls never talk.",
  "The haunted house finally sold. It had great boo-siness potential.",
  "What’s a realtor’s favorite kind of music? House music.",
  "Why did the homeowner plant money in the yard? They wanted to increase the property value.",
  "That fixer-upper and I have an understanding: it stays broken, and I keep calling it charming.",
  "Why did the real estate agent sleep so well? She had plenty of listings to count.",
  "The house wasn’t old—it was pre-loved with vintage plumbing.",
  "Why did the condo blush? It saw the townhouse next door changing its siding.",
  "Never argue with a real estate agent. They always have a lot to offer.",
  "The basement started a band. It already had the perfect underground sound.",
  "Why are realtors excellent matchmakers? They know when there’s good chemistry and great curb appeal.",
  "I asked the house how it was feeling. It said, ‘A little down in the dumps, but my spirits are rising.’",
  "What did one wall say to the other? I’ll meet you at the corner.",
  "Why did the buyer love the cul-de-sac? It was a turning point.",
  "That home had me at ‘recently reduced.’",
  "Why was the mortgage so calm? It had a fixed rate.",
  "I wanted a house with a view, but the price was overlooking my budget.",
  "Why did the realtor go broke? They lost their sense of property.",
  "This market is like a good porch: it keeps everyone on their toes and occasionally needs support.",
  "The kitchen and I clicked immediately. We had great counter chemistry.",
  "Why do houses love December? They get to put on their best closing decorations.",
  "The seller said the neighborhood was quiet. Even the price was hush-hush.",
  "I toured a home with no closets. It gave me nothing to hang onto.",
  "Why was the deed so proud? It finally had something to its name.",
  "A good real estate pun is all about location, location, location.",
  "Why did the house apply for a job? It wanted to bring home the bacon.",
  "The chimney got promoted because its performance was through the roof.",
  "I fell in love with a split-level. We’re taking our relationship one step at a time.",
  "Why did the door get an award? It was outstanding in its field—and slightly off the hinges.",
  "That listing photo had excellent exposure. The house is considering a modeling career.",
  "What do you call a real estate agent who moonlights as a gardener? A hedge fund manager.",
  "Why was the house terrible at poker? Everyone could see right through its windows.",
  "The buyer asked for room to negotiate, so we showed them the spare bedroom.",
  "Why don’t houses ever get lost? They always have an address.",
  "I made an offer on a bakery. I kneaded the dough, but the seller wanted more bread.",
  "What’s the hardest part of buying a haunted house? The possession date.",
  "The appraisal came in low, but we’re trying to value its honesty.",
  "Why did the realtor love geometry? It’s all about finding the right angle.",
  "I told my clients this home has endless possibilities. Mostly because the repairs never end."
];
